// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.pinhobrunodev.service1;

public interface EventRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EventRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Event event = 1;</code>
   * @return Whether the event field is set.
   */
  boolean hasEvent();
  /**
   * <code>.Event event = 1;</code>
   * @return The event.
   */
  Event getEvent();
  /**
   * <code>.Event event = 1;</code>
   */
  EventOrBuilder getEventOrBuilder();
}
