// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.pinhobrunodev.service2;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Event)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string eventId = 1;</code>
   * @return The eventId.
   */
  java.lang.String getEventId();
  /**
   * <code>string eventId = 1;</code>
   * @return The bytes for eventId.
   */
  com.google.protobuf.ByteString
      getEventIdBytes();

  /**
   * <code>string eventName = 2;</code>
   * @return The eventName.
   */
  java.lang.String getEventName();
  /**
   * <code>string eventName = 2;</code>
   * @return The bytes for eventName.
   */
  com.google.protobuf.ByteString
      getEventNameBytes();

  /**
   * <code>string eventImgLink = 3;</code>
   * @return The eventImgLink.
   */
  java.lang.String getEventImgLink();
  /**
   * <code>string eventImgLink = 3;</code>
   * @return The bytes for eventImgLink.
   */
  com.google.protobuf.ByteString
      getEventImgLinkBytes();

  /**
   * <code>string eventAddress = 4;</code>
   * @return The eventAddress.
   */
  java.lang.String getEventAddress();
  /**
   * <code>string eventAddress = 4;</code>
   * @return The bytes for eventAddress.
   */
  com.google.protobuf.ByteString
      getEventAddressBytes();

  /**
   * <code>string lat = 5;</code>
   * @return The lat.
   */
  java.lang.String getLat();
  /**
   * <code>string lat = 5;</code>
   * @return The bytes for lat.
   */
  com.google.protobuf.ByteString
      getLatBytes();

  /**
   * <code>string lng = 6;</code>
   * @return The lng.
   */
  java.lang.String getLng();
  /**
   * <code>string lng = 6;</code>
   * @return The bytes for lng.
   */
  com.google.protobuf.ByteString
      getLngBytes();

  /**
   * <code>repeated string categories = 7;</code>
   * @return A list containing the categories.
   */
  java.util.List<java.lang.String>
      getCategoriesList();
  /**
   * <code>repeated string categories = 7;</code>
   * @return The count of categories.
   */
  int getCategoriesCount();
  /**
   * <code>repeated string categories = 7;</code>
   * @param index The index of the element to return.
   * @return The categories at the given index.
   */
  java.lang.String getCategories(int index);
  /**
   * <code>repeated string categories = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the categories at the given index.
   */
  com.google.protobuf.ByteString
      getCategoriesBytes(int index);
}
