// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.pinhobrunodev.service2;

/**
 * Protobuf type {@code Event}
 */
public final class Event extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Event)
    EventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Event.newBuilder() to construct.
  private Event(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Event() {
    eventId_ = "";
    eventName_ = "";
    eventImgLink_ = "";
    eventAddress_ = "";
    lat_ = "";
    lng_ = "";
    categories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Event();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.pinhobrunodev.service2.CreateEventOnTrackerServiceProto.internal_static_Event_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.pinhobrunodev.service2.CreateEventOnTrackerServiceProto.internal_static_Event_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.pinhobrunodev.service2.Event.class, com.pinhobrunodev.service2.Event.Builder.class);
  }

  public static final int EVENTID_FIELD_NUMBER = 1;
  private volatile java.lang.Object eventId_;
  /**
   * <code>string eventId = 1;</code>
   * @return The eventId.
   */
  @java.lang.Override
  public java.lang.String getEventId() {
    java.lang.Object ref = eventId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventId_ = s;
      return s;
    }
  }
  /**
   * <code>string eventId = 1;</code>
   * @return The bytes for eventId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventIdBytes() {
    java.lang.Object ref = eventId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENTNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object eventName_;
  /**
   * <code>string eventName = 2;</code>
   * @return The eventName.
   */
  @java.lang.Override
  public java.lang.String getEventName() {
    java.lang.Object ref = eventName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventName_ = s;
      return s;
    }
  }
  /**
   * <code>string eventName = 2;</code>
   * @return The bytes for eventName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventNameBytes() {
    java.lang.Object ref = eventName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENTIMGLINK_FIELD_NUMBER = 3;
  private volatile java.lang.Object eventImgLink_;
  /**
   * <code>string eventImgLink = 3;</code>
   * @return The eventImgLink.
   */
  @java.lang.Override
  public java.lang.String getEventImgLink() {
    java.lang.Object ref = eventImgLink_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventImgLink_ = s;
      return s;
    }
  }
  /**
   * <code>string eventImgLink = 3;</code>
   * @return The bytes for eventImgLink.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventImgLinkBytes() {
    java.lang.Object ref = eventImgLink_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventImgLink_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENTADDRESS_FIELD_NUMBER = 4;
  private volatile java.lang.Object eventAddress_;
  /**
   * <code>string eventAddress = 4;</code>
   * @return The eventAddress.
   */
  @java.lang.Override
  public java.lang.String getEventAddress() {
    java.lang.Object ref = eventAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string eventAddress = 4;</code>
   * @return The bytes for eventAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventAddressBytes() {
    java.lang.Object ref = eventAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LAT_FIELD_NUMBER = 5;
  private volatile java.lang.Object lat_;
  /**
   * <code>string lat = 5;</code>
   * @return The lat.
   */
  @java.lang.Override
  public java.lang.String getLat() {
    java.lang.Object ref = lat_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lat_ = s;
      return s;
    }
  }
  /**
   * <code>string lat = 5;</code>
   * @return The bytes for lat.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLatBytes() {
    java.lang.Object ref = lat_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lat_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LNG_FIELD_NUMBER = 6;
  private volatile java.lang.Object lng_;
  /**
   * <code>string lng = 6;</code>
   * @return The lng.
   */
  @java.lang.Override
  public java.lang.String getLng() {
    java.lang.Object ref = lng_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lng_ = s;
      return s;
    }
  }
  /**
   * <code>string lng = 6;</code>
   * @return The bytes for lng.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLngBytes() {
    java.lang.Object ref = lng_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lng_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CATEGORIES_FIELD_NUMBER = 7;
  private com.google.protobuf.LazyStringList categories_;
  /**
   * <code>repeated string categories = 7;</code>
   * @return A list containing the categories.
   */
  public com.google.protobuf.ProtocolStringList
      getCategoriesList() {
    return categories_;
  }
  /**
   * <code>repeated string categories = 7;</code>
   * @return The count of categories.
   */
  public int getCategoriesCount() {
    return categories_.size();
  }
  /**
   * <code>repeated string categories = 7;</code>
   * @param index The index of the element to return.
   * @return The categories at the given index.
   */
  public java.lang.String getCategories(int index) {
    return categories_.get(index);
  }
  /**
   * <code>repeated string categories = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the categories at the given index.
   */
  public com.google.protobuf.ByteString
      getCategoriesBytes(int index) {
    return categories_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, eventId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, eventName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventImgLink_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, eventImgLink_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventAddress_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, eventAddress_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lat_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, lat_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lng_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, lng_);
    }
    for (int i = 0; i < categories_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, categories_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, eventId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, eventName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventImgLink_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, eventImgLink_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventAddress_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, eventAddress_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lat_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, lat_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lng_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, lng_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < categories_.size(); i++) {
        dataSize += computeStringSizeNoTag(categories_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCategoriesList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.pinhobrunodev.service2.Event)) {
      return super.equals(obj);
    }
    com.pinhobrunodev.service2.Event other = (com.pinhobrunodev.service2.Event) obj;

    if (!getEventId()
        .equals(other.getEventId())) return false;
    if (!getEventName()
        .equals(other.getEventName())) return false;
    if (!getEventImgLink()
        .equals(other.getEventImgLink())) return false;
    if (!getEventAddress()
        .equals(other.getEventAddress())) return false;
    if (!getLat()
        .equals(other.getLat())) return false;
    if (!getLng()
        .equals(other.getLng())) return false;
    if (!getCategoriesList()
        .equals(other.getCategoriesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EVENTID_FIELD_NUMBER;
    hash = (53 * hash) + getEventId().hashCode();
    hash = (37 * hash) + EVENTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getEventName().hashCode();
    hash = (37 * hash) + EVENTIMGLINK_FIELD_NUMBER;
    hash = (53 * hash) + getEventImgLink().hashCode();
    hash = (37 * hash) + EVENTADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getEventAddress().hashCode();
    hash = (37 * hash) + LAT_FIELD_NUMBER;
    hash = (53 * hash) + getLat().hashCode();
    hash = (37 * hash) + LNG_FIELD_NUMBER;
    hash = (53 * hash) + getLng().hashCode();
    if (getCategoriesCount() > 0) {
      hash = (37 * hash) + CATEGORIES_FIELD_NUMBER;
      hash = (53 * hash) + getCategoriesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.pinhobrunodev.service2.Event parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pinhobrunodev.service2.Event parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pinhobrunodev.service2.Event parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pinhobrunodev.service2.Event parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pinhobrunodev.service2.Event parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.pinhobrunodev.service2.Event parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.pinhobrunodev.service2.Event parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pinhobrunodev.service2.Event parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pinhobrunodev.service2.Event parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.pinhobrunodev.service2.Event parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.pinhobrunodev.service2.Event parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.pinhobrunodev.service2.Event parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.pinhobrunodev.service2.Event prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Event}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Event)
      com.pinhobrunodev.service2.EventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pinhobrunodev.service2.CreateEventOnTrackerServiceProto.internal_static_Event_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pinhobrunodev.service2.CreateEventOnTrackerServiceProto.internal_static_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pinhobrunodev.service2.Event.class, com.pinhobrunodev.service2.Event.Builder.class);
    }

    // Construct using com.pinhobrunodev.service2.Event.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      eventId_ = "";

      eventName_ = "";

      eventImgLink_ = "";

      eventAddress_ = "";

      lat_ = "";

      lng_ = "";

      categories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.pinhobrunodev.service2.CreateEventOnTrackerServiceProto.internal_static_Event_descriptor;
    }

    @java.lang.Override
    public com.pinhobrunodev.service2.Event getDefaultInstanceForType() {
      return com.pinhobrunodev.service2.Event.getDefaultInstance();
    }

    @java.lang.Override
    public com.pinhobrunodev.service2.Event build() {
      com.pinhobrunodev.service2.Event result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.pinhobrunodev.service2.Event buildPartial() {
      com.pinhobrunodev.service2.Event result = new com.pinhobrunodev.service2.Event(this);
      int from_bitField0_ = bitField0_;
      result.eventId_ = eventId_;
      result.eventName_ = eventName_;
      result.eventImgLink_ = eventImgLink_;
      result.eventAddress_ = eventAddress_;
      result.lat_ = lat_;
      result.lng_ = lng_;
      if (((bitField0_ & 0x00000001) != 0)) {
        categories_ = categories_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.categories_ = categories_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.pinhobrunodev.service2.Event) {
        return mergeFrom((com.pinhobrunodev.service2.Event)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.pinhobrunodev.service2.Event other) {
      if (other == com.pinhobrunodev.service2.Event.getDefaultInstance()) return this;
      if (!other.getEventId().isEmpty()) {
        eventId_ = other.eventId_;
        onChanged();
      }
      if (!other.getEventName().isEmpty()) {
        eventName_ = other.eventName_;
        onChanged();
      }
      if (!other.getEventImgLink().isEmpty()) {
        eventImgLink_ = other.eventImgLink_;
        onChanged();
      }
      if (!other.getEventAddress().isEmpty()) {
        eventAddress_ = other.eventAddress_;
        onChanged();
      }
      if (!other.getLat().isEmpty()) {
        lat_ = other.lat_;
        onChanged();
      }
      if (!other.getLng().isEmpty()) {
        lng_ = other.lng_;
        onChanged();
      }
      if (!other.categories_.isEmpty()) {
        if (categories_.isEmpty()) {
          categories_ = other.categories_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureCategoriesIsMutable();
          categories_.addAll(other.categories_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              eventId_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              eventName_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              eventImgLink_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              eventAddress_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 42: {
              lat_ = input.readStringRequireUtf8();

              break;
            } // case 42
            case 50: {
              lng_ = input.readStringRequireUtf8();

              break;
            } // case 50
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureCategoriesIsMutable();
              categories_.add(s);
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object eventId_ = "";
    /**
     * <code>string eventId = 1;</code>
     * @return The eventId.
     */
    public java.lang.String getEventId() {
      java.lang.Object ref = eventId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string eventId = 1;</code>
     * @return The bytes for eventId.
     */
    public com.google.protobuf.ByteString
        getEventIdBytes() {
      java.lang.Object ref = eventId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string eventId = 1;</code>
     * @param value The eventId to set.
     * @return This builder for chaining.
     */
    public Builder setEventId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      eventId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string eventId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventId() {
      
      eventId_ = getDefaultInstance().getEventId();
      onChanged();
      return this;
    }
    /**
     * <code>string eventId = 1;</code>
     * @param value The bytes for eventId to set.
     * @return This builder for chaining.
     */
    public Builder setEventIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      eventId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object eventName_ = "";
    /**
     * <code>string eventName = 2;</code>
     * @return The eventName.
     */
    public java.lang.String getEventName() {
      java.lang.Object ref = eventName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string eventName = 2;</code>
     * @return The bytes for eventName.
     */
    public com.google.protobuf.ByteString
        getEventNameBytes() {
      java.lang.Object ref = eventName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string eventName = 2;</code>
     * @param value The eventName to set.
     * @return This builder for chaining.
     */
    public Builder setEventName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      eventName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string eventName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventName() {
      
      eventName_ = getDefaultInstance().getEventName();
      onChanged();
      return this;
    }
    /**
     * <code>string eventName = 2;</code>
     * @param value The bytes for eventName to set.
     * @return This builder for chaining.
     */
    public Builder setEventNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      eventName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object eventImgLink_ = "";
    /**
     * <code>string eventImgLink = 3;</code>
     * @return The eventImgLink.
     */
    public java.lang.String getEventImgLink() {
      java.lang.Object ref = eventImgLink_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventImgLink_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string eventImgLink = 3;</code>
     * @return The bytes for eventImgLink.
     */
    public com.google.protobuf.ByteString
        getEventImgLinkBytes() {
      java.lang.Object ref = eventImgLink_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventImgLink_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string eventImgLink = 3;</code>
     * @param value The eventImgLink to set.
     * @return This builder for chaining.
     */
    public Builder setEventImgLink(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      eventImgLink_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string eventImgLink = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventImgLink() {
      
      eventImgLink_ = getDefaultInstance().getEventImgLink();
      onChanged();
      return this;
    }
    /**
     * <code>string eventImgLink = 3;</code>
     * @param value The bytes for eventImgLink to set.
     * @return This builder for chaining.
     */
    public Builder setEventImgLinkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      eventImgLink_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object eventAddress_ = "";
    /**
     * <code>string eventAddress = 4;</code>
     * @return The eventAddress.
     */
    public java.lang.String getEventAddress() {
      java.lang.Object ref = eventAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string eventAddress = 4;</code>
     * @return The bytes for eventAddress.
     */
    public com.google.protobuf.ByteString
        getEventAddressBytes() {
      java.lang.Object ref = eventAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string eventAddress = 4;</code>
     * @param value The eventAddress to set.
     * @return This builder for chaining.
     */
    public Builder setEventAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      eventAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string eventAddress = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventAddress() {
      
      eventAddress_ = getDefaultInstance().getEventAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string eventAddress = 4;</code>
     * @param value The bytes for eventAddress to set.
     * @return This builder for chaining.
     */
    public Builder setEventAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      eventAddress_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lat_ = "";
    /**
     * <code>string lat = 5;</code>
     * @return The lat.
     */
    public java.lang.String getLat() {
      java.lang.Object ref = lat_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lat_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lat = 5;</code>
     * @return The bytes for lat.
     */
    public com.google.protobuf.ByteString
        getLatBytes() {
      java.lang.Object ref = lat_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lat_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lat = 5;</code>
     * @param value The lat to set.
     * @return This builder for chaining.
     */
    public Builder setLat(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lat_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string lat = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLat() {
      
      lat_ = getDefaultInstance().getLat();
      onChanged();
      return this;
    }
    /**
     * <code>string lat = 5;</code>
     * @param value The bytes for lat to set.
     * @return This builder for chaining.
     */
    public Builder setLatBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lat_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lng_ = "";
    /**
     * <code>string lng = 6;</code>
     * @return The lng.
     */
    public java.lang.String getLng() {
      java.lang.Object ref = lng_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lng_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lng = 6;</code>
     * @return The bytes for lng.
     */
    public com.google.protobuf.ByteString
        getLngBytes() {
      java.lang.Object ref = lng_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lng_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lng = 6;</code>
     * @param value The lng to set.
     * @return This builder for chaining.
     */
    public Builder setLng(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lng_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string lng = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLng() {
      
      lng_ = getDefaultInstance().getLng();
      onChanged();
      return this;
    }
    /**
     * <code>string lng = 6;</code>
     * @param value The bytes for lng to set.
     * @return This builder for chaining.
     */
    public Builder setLngBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lng_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList categories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureCategoriesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        categories_ = new com.google.protobuf.LazyStringArrayList(categories_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string categories = 7;</code>
     * @return A list containing the categories.
     */
    public com.google.protobuf.ProtocolStringList
        getCategoriesList() {
      return categories_.getUnmodifiableView();
    }
    /**
     * <code>repeated string categories = 7;</code>
     * @return The count of categories.
     */
    public int getCategoriesCount() {
      return categories_.size();
    }
    /**
     * <code>repeated string categories = 7;</code>
     * @param index The index of the element to return.
     * @return The categories at the given index.
     */
    public java.lang.String getCategories(int index) {
      return categories_.get(index);
    }
    /**
     * <code>repeated string categories = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the categories at the given index.
     */
    public com.google.protobuf.ByteString
        getCategoriesBytes(int index) {
      return categories_.getByteString(index);
    }
    /**
     * <code>repeated string categories = 7;</code>
     * @param index The index to set the value at.
     * @param value The categories to set.
     * @return This builder for chaining.
     */
    public Builder setCategories(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCategoriesIsMutable();
      categories_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string categories = 7;</code>
     * @param value The categories to add.
     * @return This builder for chaining.
     */
    public Builder addCategories(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCategoriesIsMutable();
      categories_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string categories = 7;</code>
     * @param values The categories to add.
     * @return This builder for chaining.
     */
    public Builder addAllCategories(
        java.lang.Iterable<java.lang.String> values) {
      ensureCategoriesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, categories_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string categories = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCategories() {
      categories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string categories = 7;</code>
     * @param value The bytes of the categories to add.
     * @return This builder for chaining.
     */
    public Builder addCategoriesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureCategoriesIsMutable();
      categories_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Event)
  }

  // @@protoc_insertion_point(class_scope:Event)
  private static final com.pinhobrunodev.service2.Event DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.pinhobrunodev.service2.Event();
  }

  public static com.pinhobrunodev.service2.Event getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Event>
      PARSER = new com.google.protobuf.AbstractParser<Event>() {
    @java.lang.Override
    public Event parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Event> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Event> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.pinhobrunodev.service2.Event getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

